---

- name: Get Info on a Backend Bucket as Default Backend
  google.cloud.gcp_compute_backend_bucket_info:
    filters:
    - name = {{ cloud_provider_resource_detail.backend_name }}
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
  register: default_service

- name: Create a URL Map
  google.cloud.gcp_compute_url_map:
    name: "{{ cloud_provider_resource_detail.url_map_name }}"
    default_service: "{{ default_service.resources[0] }}"
    host_rules: "{{ cloud_provider_resource_detail.host_rules | default(omit) }}"
    path_matchers: "{{ cloud_provider_resource_detail.path_matchers | default(omit) }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: present
  register: url_map

- name: Create a Target HTTPS Proxy
  google.cloud.gcp_compute_target_https_proxy:
    name: "{{ cloud_provider_resource_detail.target_https_proxy_name }}"
    ssl_certificates:
    - "{{ ssl_cert.resources[0] }}"
    - "{{ ssl_cert_event.resources[0] }}"
    url_map: "{{ url_map }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: present