---
- name: Resource Creation
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/{{ cloud_provider | lower }}/{{ item }}/main.yml"
  when:
    - cloud_provider_resource_type is defined
  loop: "{{ cloud_provider_resource_type }}"
