---
- name: Resource Creation
  ansible.builtin.include_tasks: "{{ cloud_provider }}/{{ item }}/main.yml"
  when:
    - cloud_provider_resource_type is defined
  loop: "{{ cloud_provider_resource_type }}"
