---
- name: Init Instance Group Output
  ansible.builtin.set_fact:
    output_compute_instance_group: null
  when: with_output is defined and with_output and output_compute_instance_group is not defined

- name: Create a Instance Group
  google.cloud.gcp_compute_instance_group:
    name: "{{ cloud_provider_resource_detail.compute_instance_group.name }}"
    description: "{{ cloud_provider_resource_detail.compute_instance_group.description | default(omit) }}"
    region: "{{ cloud_provider_resource_detail.compute_instance_group.region | default(omit) }}"
    zone: "{{ cloud_provider_resource_detail.compute_instance_group.zone }}"
    env_type: "{{ cloud_provider_resource_detail.compute_instance_group.env_type | default(omit) }}"
    instances: "{{ cloud_provider_resource_detail.compute_instance_group.instances | default(omit) }}"
    named_ports: "{{ cloud_provider_resource_detail.compute_instance_group.named_ports | default(omit) }}"
    network: "{{ cloud_provider_resource_detail.compute_instance_group.network | default(omit) }}"
    subnetwork: "{{ cloud_provider_resource_detail.compute_instance_group.subnetwork | default(omit) }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: "present"
  register: compute_instance_group_result
  
# set_fact to print output globally
- name: Set Instance Group Output
  set_fact:
    output_compute_instance_group: "{{ output_compute_instance_group | combine({ cloud_provider_resource_detail.compute_instance_group.name : compute_instance_group_result }, recursive=True) }}"
  when: with_output is defined and with_output