---
- name: Create a Disk
  google.cloud.gcp_compute_disk:
    name: "{{ cloud_provider_resource_detail.disk_name }}"
    size_gb: "{{ cloud_provider_resource_detail.size_gb }}"
    source_image: "{{ cloud_provider_resource_detail.source_image }}"
    zone: "{{ cloud_provider_resource_detail.zone }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: "{{ state | default('present') }}"