---
- name: Set Certificates
  ansible.builtin.set_fact:
    __certificates: []

- name: Get Info on a SSL Certificate
  google.cloud.gcp_compute_ssl_certificate_info:
    filters:
    - name = {{ cloud_provider_resource_detail.certificate_name }}
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
  register: certificate

- with_items: Append Certificate
  set_fact:
    __certificates: "{{ __certificates|default([]) + [ certificate.resources[0] ] }}"
  
- name: Debug Print Variables
  ansible.builtin.debug:
    msg: "{{ __certificates }}"