---
- name: Init Backend Bucket Output
  ansible.builtin.set_fact:
    output_backend_bucket: null
  when: with_output is defined and with_output and output_backend_bucket is not defined

- name: Create a Backend Bucket
  google.cloud.gcp_compute_backend_bucket:
    name: "{{ cloud_provider_resource_detail.backend_bucket.name }}"
    bucket_name: "{{ cloud_provider_resource_detail.storage_bucket.name }}"
    description: "{{ cloud_provider_resource_detail.backend_bucket.description }}"
    env_type: "{{ cloud_provider_resource_detail.backend_bucket.env_type | default(omit) }}"
    enable_cdn: "{{ cloud_provider_resource_detail.backend_bucket.enable_cdn | default('true') }}"
    cdn_policy: "{{ cloud_provider_resource_detail.backend_bucket.cdn_policy | default(omit) }}"
    custom_response_headers: "{{ cloud_provider_resource_detail.backend_bucket.custom_response_headers | default(omit) }}"
    scopes: "{{ cloud_provider_resource_detail.backend_bucket.scopes | default(omit) }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: present
  register: backend_bucket_result

# set_fact to print output globally
- name: Set Backend Bucket Output
  set_fact:
    output_backend_bucket: "{{ output_backend_bucket | combine({ cloud_provider_resource_detail.backend_bucket.name : backend_bucket_result }, recursive=True) }}"
  when: with_output is defined and with_output
