---
- name: Delete a Disk
  google.cloud.gcp_compute_disk:
    name: "{{ cloud_provider_resource_detail.compute_disk.name }}"
    size_gb: "{{ cloud_provider_resource_detail.compute_disk.size_gb }}"
    source_image: "{{ cloud_provider_resource_detail.compute_disk.source_image }}"
    zone: "{{ cloud_provider_resource_detail.compute_disk.zone }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: absent