---
- name: Init Disk Output
  ansible.builtin.set_fact:
    output_compute_disk: null
  when: with_output is defined and with_output and output_compute_disk is not defined

- name: Create a Disk
  google.cloud.gcp_compute_disk:
    name: "{{ cloud_provider_resource_detail.compute_disk.name }}"
    type: "{{ cloud_provider_resource_detail.compute_disk.type | default(omit) }}"
    size_gb: "{{ cloud_provider_resource_detail.compute_disk.size_gb }}"
    source_image: "{{ cloud_provider_resource_detail.compute_disk.source_image }}"
    zone: "{{ cloud_provider_resource_detail.compute_disk.zone }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: present
  register: compute_disk_result

# set_fact to print output globally
- name: Set Disk Output
  set_fact:
    output_compute_disk: "{{ output_compute_disk | combine({ cloud_provider_resource_detail.compute_disk.name : compute_disk_result }, recursive=True) }}"
  when: with_output is defined and with_output