---
- name: Init Custom Role Output
  ansible.builtin.set_fact:
    output_resourcemanager_project: null
  when: with_output is defined and with_output and output_resourcemanager_project is not defined

- name: Create a GCP Project
  google.cloud.gcp_resourcemanager_project:
    id: "{{ cloud_provider_resource_detail.resourcemanager_project.id }}"
    name: "{{ cloud_provider_resource_detail.resourcemanager_project.name }}"
    env_type: "{{ cloud_provider_resource_detail.resourcemanager_project.env_type | default(omit) }}"
    parent: "{{ cloud_provider_resource_detail.resourcemanager_project.parent | default(omit) }}"
    labels: "{{ cloud_provider_resource_detail.resourcemanager_project.labels | default(omit) }}"
    scopes: "{{ cloud_provider_resource_detail.resourcemanager_project.scopes | default(omit) }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: "present"
  register: resourcemanager_project_result

# set_fact to print output globally
- name: Set Custom Role Output
  set_fact:
    output_resourcemanager_project: "{{ output_resourcemanager_project | combine({ cloud_provider_resource_detail.resourcemanager_project.name : resourcemanager_project_result }, recursive=True) }}"
  when: with_output is defined and with_output