---
- name: Delete a Bucket
  google.cloud.gcp_storage_bucket:
    name: "{{ cloud_provider_resource_detail.storage_bucket.name }}"
    storage_class: "{{ cloud_provider_resource_detail.storage_bucket.storage_class | default('STANDARD') }}"
    location: "{{ cloud_provider_resource_detail.storage_bucket.location | default(omit) }}"
    predefined_default_object_acl: "{{ cloud_provider_resource_detail.storage_bucket.predefined_default_object_acl | default('projectPrivate') }}"
    cors: "{{ cloud_provider_resource_detail.storage_bucket.cors | default(omit) }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: absent