---

- name: Delete a KVM Virtual Machine
  community.proxmox.proxmox_kvm:
    # Authentication parameters 
    api_user: "{{ cloud_provider_auth.api_user }}"
    api_token_id: "{{ cloud_provider_auth.api_token_id }}"
    api_token_secret: "{{ cloud_provider_auth.api_token_secret }}"
    api_host: "{{ cloud_provider_auth.api_host }}"
    api_timeout: "{{ cloud_provider_auth.api_timeout | default(180) }}"
    # Authentication parameters
    
    # KVM Virtual Machine parameters
    vmid: "{{ cloud_provider_resource_detail.vmid | default(omit) }}"
    # KVM Virtual Machine parameters
    state: absent