---
- name: Manage External Compute Address
  hosts: localhost
  gather_facts: false
  
  vars:
    cloud_provider: "gcp"
    cloud_provider_resource_type:
      - "compute-address"
    cloud_provider_auth:
      project_id: "dpanel-dev"
      auth_kind: "serviceaccount"
      service_acount_token: "./gcp-credential.json"
    cloud_provider_resource_detail:
      compute_address:
        name: "dpanel-example-compute-address"
        region: "asia-southeast2"
        address_type: "EXTERNAL"
        network_tier: "PREMIUM"


  roles:
    - role: dpanel.cloud-provider
