---
- name: Create a Service Account
  google.cloud.gcp_iam_service_account:
    name: "sa-{{ cloud_provider_resource_detail.sa_name }}@{{ cloud_provider_auth.project_id }}.google.com.iam.gserviceaccount.com"
    display_name: "{{ cloud_provider_resource_detail.display_name }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: present
