---

- block:
  - name: Delete a Backend Bucket
    google.cloud.gcp_compute_backend_bucket:
      name: "{{ cloud_provider_resource_detail.backend_bucket.name }}"
      bucket_name: "{{ cloud_provider_resource_detail.bucket_name }}"
      description: "{{ cloud_provider_resource_detail.backend_bucket.description }}"
      enable_cdn: "{{ cloud_provider_resource_detail.backend_bucket.enable_cdn | default('true') }}"
      project: "{{ cloud_provider_auth.project_id }}"
      auth_kind: "{{ cloud_provider_auth.auth_kind }}"
      service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
      state: absent
  when: cloud_provider_resource_detail.backend_bucket is defined


- name: Delete a Bucket
  google.cloud.gcp_storage_bucket:
    name: "{{ cloud_provider_resource_detail.bucket_name }}"
    storage_class: "{{ cloud_provider_resource_detail.storage_class | default('STANDARD') }}"
    location: "{{ cloud_provider_resource_detail.location | default(omit) }}"
    predefined_default_object_acl: "{{ cloud_provider_resource_detail.predefined_default_object_acl | default('projectPrivate') }}"
    cors: "{{ cloud_provider_resource_detail.cors | default(omit) }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: absent