---
- name: Create a Bucket
  google.cloud.gcp_storage_bucket:
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    name: "{{ cloud_provider_resource_detail.bucket_name }}"
    storage_class: "{{ cloud_provider_resource_detail.storage_class | default('STANDARD') }}"
    location: "{{ cloud_provider_resource_detail.location | default('asia-southeast2') }}"
    predefined_default_object_acl: "{{ cloud_provider_resource_detail.predefined_default_object_acl | default('projectPrivate') }}"
    cors: "{{ cloud_provider_resource_detail.cors | default({}) }}"
    state: present
  register: bucket

# Storage Legacy Bucket Reader
- block:
  - name: Legacy - Create a Bucket Access Control
    google.cloud.gcp_storage_bucket_access_control:
      bucket: "{{ bucket }}"
      entity: "{{ cloud_provider_resource_detail.acl.entity | default('allAuthenticatedUsers') }}"
      role: "{{ cloud_provider_resource_detail.acl.role | default('READER') }}"
      project: "{{ cloud_provider_auth.project_id }}"
      auth_kind: "{{ cloud_provider_auth.auth_kind }}"
      service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
      state: present
  when: cloud_provider_resource_detail.acl is defined

# Backend buckets allow you to use Google Cloud Storage buckets with HTTP(S) load balancing.
- block:
  - name: Create a Backend Bucket
    google.cloud.gcp_compute_backend_bucket:
      name: "{{ cloud_provider_resource_detail.backend_bucket.name }}"
      bucket_name: "{{ bucket.name }}"
      description: "{{ cloud_provider_resource_detail.backend_bucket.description }}"
      enable_cdn: "{{ cloud_provider_resource_detail.backend_bucket.enable_cdn | default('true') }}"
      project: "{{ cloud_provider_auth.project_id }}"
      auth_kind: "{{ cloud_provider_auth.auth_kind }}"
      service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
      state: present
  when: cloud_provider_resource_detail.backend_bucket is defined
