---
- name: Manage a Default Network
  hosts: localhost
  gather_facts: false

  vars:
    cloud_provider: "gcp"
    cloud_provider_resource_type:
      - "network"
    cloud_provider_auth:
      project_id: "dpanel-dev"
      auth_kind: "serviceaccount"
      service_acount_token: "./gcp-credential.json"
    cloud_provider_resource_detail:
      compute_network:
        name: "dpanel-example-network"
        auto_create_subnetworks: true

  roles:
    - role: dpanel.cloud-provider
