---
- name: Manage a Compute Disk
  hosts: localhost
  gather_facts: false

  vars:
    cloud_provider: "gcp"
    cloud_provider_resource_type:
      - "compute-disk"
    cloud_provider_auth:
      project_id: "dpanel-dev"
      auth_kind: "serviceaccount"
      service_acount_token: "./gcp-credential.json"
    cloud_provider_resource_detail:
      compute_disk:
        name: "dpanel-example-compute-disk"
        type: "pd-standard"
        source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-minimal-2404-lts-amd64"
        zone: "asia-southeast2-a"
        size_gb: 20

  roles:
    - role: dpanel.cloud-provider
