---
- name: Create a Custom Role
  google.cloud.gcp_iam_role:
    name: "{{ cloud_provider_resource_detail.role_name }}"
    title: "{{ cloud_provider_resource_detail.title }}"
    description: "{{ cloud_provider_resource_detail.description }}"
    included_permissions: "{{ cloud_provider_resource_detail.included_permissions }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: "{{ state | default('present') }}"
