---
- name: Create a Kubernetes Cluster
  google.cloud.gcp_container_cluster:
    name: "{{ cloud_provider_resource_detail.kube_cluster_name }}"
    initial_node_count: "{{ cloud_provider_resource_detail.initial_node_count }}"
    node_config: "{{ cloud_provider_resource_detail.node_config }}"
    location: "{{ cloud_provider_resource_detail.location }}"
    subnetwork: "{{ cloud_provider_resource_detail.subnetwork | default('') }}"
    initial_cluster_version: "{{ cloud_provider_resource_detail.initial_cluster_version }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: present
  register: cluster

- name: Create a Node Pool
  google.cloud.gcp_container_node_pool:
    name: "{{ cloud_provider_resource_detail.pool_name }}"
    initial_node_count: "{{ cloud_provider_resource_detail.initial_node_count }}"
    cluster: "{{ cluster }}"
    location: "{{ cloud_provider_resource_detail.location }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: present