---
- name: Delete a SSL/TLS Certificate
  google.cloud.gcp_compute_ssl_certificate:
    type: "{{ cloud_provider_resource_detail.certificate.type | default(omit) }}"
    name: "{{ cloud_provider_resource_detail.certificate.name }}"
    description: "{{ cloud_provider_resource_detail.certificate.description }}"
    managed: "{{ cloud_provider_resource_detail.certificate.managed | default(omit) }}"
    certificate: "{{ cloud_provider_resource_detail.certificate.pem | default(omit) }}"
    private_key: "{{ cloud_provider_resource_detail.certificate.private | default(omit) }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: absent