---
- name: Create a GCP Project
  google.cloud.gcp_resourcemanager_project:
    id: "{{ cloud_provider_auth.project_id }}"
    name: "{{ cloud_provider_resource_detail.project_name }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    parent:
      type: organization
      id: "{{ cloud_provider_resource_detail.parent_id }}"
    state: "{{ cloud_provider_resource_detail.state | default('present') }}"
