---
- name: Delete a SQL Instance
  google.cloud.gcp_sql_instance:
    name: "{{ cloud_provider_resource_detail.sql_instance.name }}"
    env_type: "{{ cloud_provider_resource_detail.sql_instance.env_type | default(omit) }}"
    backend_type: "{{ cloud_provider_resource_detail.sql_instance.backend_type | default(omit) }}"
    connection_name: "{{ cloud_provider_resource_detail.sql_instance.connection_name | default(omit) }}"
    database_version: "{{ cloud_provider_resource_detail.sql_instance.database_version | default(omit) }}"
    root_password: "{{ cloud_provider_resource_detail.sql_instance.root_password | default(omit) }}"
    instance_type: "{{ cloud_provider_resource_detail.sql_instance.instance_type | default(omit) }}"
    failover_replica: "{{ cloud_provider_resource_detail.sql_instance.failover_replica | default(omit) }}"
    disk_encryption_configuration: "{{ cloud_provider_resource_detail.sql_instance.disk_encryption_configuration | default(omit) }}"
    disk_encryption_status: "{{ cloud_provider_resource_detail.sql_instance.disk_encryption_status | default(omit) }}"
    region: "{{ cloud_provider_resource_detail.sql_instance.region | default(omit) }}"
    ipv6_address: "{{ cloud_provider_resource_detail.sql_instance.ipv6_address | default(omit) }}"
    settings: "{{ cloud_provider_resource_detail.sql_instance.settings | default(omit) }}"
    replica_configuration: "{{ cloud_provider_resource_detail.sql_instance.replica_configuration | default(omit) }}"
    master_instance_name: "{{ cloud_provider_resource_detail.sql_instance.master_instance_name | default(omit) }}"
    max_disk_size: "{{ cloud_provider_resource_detail.sql_instance.max_disk_size | default(omit) }}"
    scopes: "{{ cloud_provider_resource_detail.sql_instance.scopes | default(omit) }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: "absent"