---
- name: Init HTTP Proxy Output
  ansible.builtin.set_fact:
    output_target_https_proxy: null
  when: with_output is defined and with_output and output_target_https_proxy is not defined

- name: Create a Target HTTPS Proxy
  google.cloud.gcp_compute_target_https_proxy:
    name: "{{ cloud_provider_resource_detail.target_https_proxy.name }}"
    url_map: "{{ cloud_provider_resource_detail.target_https_proxy.url_map }}"
    ssl_certificates: "{{ cloud_provider_resource_detail.target_https_proxy.ssl_certificates }}"
    description: "{{ cloud_provider_resource_detail.target_https_proxy.description | default(omit) }}"
    ssl_policy: "{{ cloud_provider_resource_detail.target_https_proxy.ssl_policy | default(omit) }}"
    env_type: "{{ cloud_provider_resource_detail.target_https_proxy.env_type | default(omit) }}"
    proxy_bind: "{{ cloud_provider_resource_detail.target_https_proxy.proxy_bind | default(omit) }}"
    quic_override: "{{ cloud_provider_resource_detail.target_https_proxy.quic_override | default(omit) }}"
    scopes: "{{ cloud_provider_resource_detail.target_https_proxy.scopes | default(omit) }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: present
  register: target_https_proxy_result

# set_fact to print output globally
- name: Set HTTP Proxy Output
  set_fact:
    output_target_https_proxy: "{{ output_target_https_proxy | combine({ cloud_provider_resource_detail.target_https_proxy.name : target_https_proxy_result }, recursive=True) }}"
  when: with_output is defined and with_output
