---
- name: Create a Subnetwork
  google.cloud.gcp_compute_subnetwork:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    env_type: "{{ item.env_type | default(omit) }}"
    region: "{{ item.region }}"
    network: "{{ cloud_provider_resource_detail.compute_subnetwork.network }}"
    ip_cidr_range: "{{ item.ip_cidr_range }}"
    secondary_ip_ranges: "{{ item.secondary_ip_ranges | default(omit) }}"
    private_ip_google_access: "{{ item.private_ip_google_access | default(omit) }}"
    private_ipv6_google_access: "{{ item.private_ipv6_google_access | default(omit) }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: "present"
  with_items: "{{ cloud_provider_resource_detail.compute_subnetwork.subnetworks }}"
