---
- name: Delete a Health Check
  google.cloud.gcp_compute_http_health_check:
    name: "{{ cloud_provider_resource_detail.compute_http_health_check.name }}"
    description: "{{ cloud_provider_resource_detail.compute_http_health_check.description | default(omit) }}"
    env_type: "{{ cloud_provider_resource_detail.compute_http_health_check.env_type | default(omit) }}"
    healthy_threshold: "{{ cloud_provider_resource_detail.compute_http_health_check.healthy_threshold | default(omit) }}"
    timeout_sec: "{{ cloud_provider_resource_detail.compute_http_health_check.timeout_sec | default(omit) }}"
    unhealthy_threshold: "{{ cloud_provider_resource_detail.compute_http_health_check.unhealthy_threshold | default(omit) }}"
    host: "{{ cloud_provider_resource_detail.compute_http_health_check.host | default(omit) }}"
    port: "{{ cloud_provider_resource_detail.compute_http_health_check.port | default(omit) }}"
    request_path: "{{ cloud_provider_resource_detail.compute_http_health_check.request_path | default(omit) }}"
    scopes: "{{ cloud_provider_resource_detail.compute_http_health_check.scopes | default(omit) }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: "absent"