---
- name: Init HTTP Health Check Output
  ansible.builtin.set_fact:
    output_compute_http_health_check: null
  when: with_output is defined and with_output and output_compute_http_health_check is not defined

- name: Create a HTTP Health Check
  google.cloud.gcp_compute_http_health_check:
    name: "{{ cloud_provider_resource_detail.compute_http_health_check.name }}"
    description: "{{ cloud_provider_resource_detail.compute_http_health_check.description | default(omit) }}"
    env_type: "{{ cloud_provider_resource_detail.compute_http_health_check.env_type | default(omit) }}"
    healthy_threshold: "{{ cloud_provider_resource_detail.compute_http_health_check.healthy_threshold | default(omit) }}"
    timeout_sec: "{{ cloud_provider_resource_detail.compute_http_health_check.timeout_sec | default(omit) }}"
    unhealthy_threshold: "{{ cloud_provider_resource_detail.compute_http_health_check.unhealthy_threshold | default(omit) }}"
    host: "{{ cloud_provider_resource_detail.compute_http_health_check.host | default(omit) }}"
    port: "{{ cloud_provider_resource_detail.compute_http_health_check.port | default(omit) }}"
    request_path: "{{ cloud_provider_resource_detail.compute_http_health_check.request_path | default(omit) }}"
    scopes: "{{ cloud_provider_resource_detail.compute_http_health_check.scopes | default(omit) }}"
    project: "{{ cloud_provider_auth.project_id }}"
    auth_kind: "{{ cloud_provider_auth.auth_kind }}"
    service_account_file: "{{ cloud_provider_auth.service_acount_token }}"
    state: "present"
  register: compute_http_health_check_result
  
# set_fact to print output globally
- name: Set HTTP Health Check Output
  set_fact:
    output_compute_http_health_check: "{{ output_compute_http_health_check | combine({ cloud_provider_resource_detail.compute_http_health_check.name : compute_http_health_check_result }, recursive=True) }}"
  when: with_output is defined and with_output